version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: my_mongo_container_1
    restart: unless-stopped
    ports:
      - "27018:27017"

  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo
    command: bash -c "sleep 2 && node app.js"

