version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: gatways_mongo_container
    restart: unless-stopped
    ports:
      - "27017:27017"

  gateways:
    build: .
    depends_on:
      - mongo
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

