version: '3.9'

services:
  mongo:
    image: mongo
    container_name: my_mongo
    restart: always
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo
